config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "lists#index"
  resources :lists, only: [:show, :edit, :new, :create] do
    resources :movies, only: [:show]
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_presence_of :movie_id, :list_id
  validates :movie_id, uniqueness: { scope: :list_id,
    message: "this combination has been taken"}
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :restrict_with_exception
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true
  validates :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :list
private
  def list
    @list = List.first
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @list = List.find(params[:list_id])
    result = @list.bookmarks.create(bookmark_params)
    if result.valid?
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = Movie.first(12)
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-5">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.input :movie_id, as: :select, collection: @movies %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="navbar-lewagon sticky-top navbar-expand-md" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
    <div class="row ps-5 align-items-center">
      <div class="col-md-3">
        <h1> <%= link_to image_tag('catflix.png'), root_path %></h1>
        <p class="tagline">Add a cat. Ruin a film.</p>
      </div>
      <div class="col-md-7">
          <h2 class="fw-bold"><%= @list.name %></h2>
      </div>
      <div class="col-md-2 align-items-top text-decoration-none">
        <%= link_to new_list_path do  %>
          <div class="d-flex">
            <i class="fa-solid fa-circle-plus" style="color:white; margin-right:10px; margin-top:5px;"></i>
            <p style="margin: 0;">Add List</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
   <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <% @lists.each do |list| %>
      <div class = "col-md-4">
        <%= link_to list_path(list) do %>
          <div class = "list-card" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.63)), url(<%= list.image_url %>); background-size: contain;">
          <h2><%= list.name %></h2>
        </div>
        <% end %>
      </div>
    <% end %>
</span>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-5">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class = "d-flex flex-row-reverse pb-5 pt-5">
      <div class = "btn btn-primary text-gray">
        <i class="fa-solid fa-circle-plus" style="color:$gray; margin-right:10px; margin-top:5px;"></i>
        <%= link_to "add a cat movie", new_list_bookmark_path(@list) %>
      </div>
  </div>
  <div class="row">
        <% @movies.each do |movie| %>
          <div class="col-md-3 mb-4 height-100">
            <div class="card-movie">
              <img src ="<%= src=movie.poster_url %>">
                <div class="card-movie-infos">
                  <% if movie.title.include?(' ')  %>
                    <% movie.title = movie.title.gsub(/\W/, ' Cat ') %>
                  <% else %>
                    <% movie.title = movie.title.gsub(/\z/, ' Cat ') %>
                  <% end %>
                  <h2><%= movie.title %></h2>
                    <h2><%= @bookmark.comment %></h2>
                </div>
            </div>
          </div>
        <% end %>
  </div>
</div>